name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
